### ISSUE TITLE
TypeScript path mapping is not working.

### ISSUE THREAD

**Issue by lightyen** [swc-project/swc-node#626]
#### Output

```sh
Error: Cannot find module 'x/t'
```

#### Reproduction

- https://github.com/lightyen/swc-node-path-mapping

**Comment by dmregister** [comment]
@Brooooooklyn is this still an issue? If so, is there a workaround?

One thing I did notice is, there isn't a way to pass paths through to swc-node/core. When I add paths to the `tsCompilerOptionsToSwcConfig`, that's when I get the Cannot find module error. Otherwise I basically get Deprecation warnings on startup, but I dont actually need to have the dist folder built:
```
(node:87854) [DEP0128] DeprecationWarning: Invalid 'main' field in '...package.json' of 'dist/index.js'. Please either fix that or report it to the module author
```

**Comment by Brooooooklyn** [comment]
@dmregister thanks for your report, I'll check it
